name: .NET Core HELLO WORLD IS TESTING

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/NewTypes/NewTypes.csproj --verbosity d
    - name: Build
      run: dotnet build src/NewTypes/NewTypes.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test test/NewTypesTest/NewTypesTest.csproj